name: Dev - Build and Deploy to KIND

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!infra/**" # Ignore changes only inside infra
  workflow_dispatch:

permissions:
  contents: write
  issues: read
  packages: write

jobs:
  build-and-deploy-dev:
    name: Build and Deploy Dev
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 📦 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔥 Build Docker Image for Development
        run: |
          docker build -t user_service:dev -f docker/Dockerfile .

      - name: 📥 Download redeploy_service.sh
        run: |
          curl -o redeploy_service.sh https://raw.githubusercontent.com/raghurammutya/infra/main/scripts/redeploy_service.sh
          chmod +x redeploy_service.sh

      - name: ⚡ Load Image into KIND
        run: |
          kind load docker-image user_service:dev

      - name: 🚀 Redeploy on KIND
        run: |
          ./redeploy_service.sh user-service

  changelog:
    name: 📋 Generate Changelog
    needs: build-and-deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 📋 Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
